# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovfrPjb-vsPrwOQQ1yUGLW5nTxO17Cvp
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')

import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/Dataset Chatbot - Form Responses 1.csv")

def remove_punc(sentence):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

    no_punct = ""
    for char in sentence:
      if char not in punctuations:
          no_punct = no_punct + char
    return no_punct

questions=list(df["Question?"].values)
q=[remove_punc(ques).strip().lower() for ques in questions]
questions=q

answers=list(df["Answer"].values)
question_embeddings = model.encode(questions)

import scipy
query = 'which sports are good at iit mandi'
query = remove_punc(query).strip().lower()
queries = [query]
query_embeddings = model.encode(queries)

threshhold = 0.8

for query, query_embedding in zip(queries, query_embeddings):
    distances = scipy.spatial.distance.cdist([query_embedding], question_embeddings, "cosine")[0]

    results = zip(range(len(distances)), distances)
    results = sorted(results, key=lambda x: x[1])

    idx, distance =results[0]
    if (1-distance)>threshhold:
      print(f"Answer with prob={1-distance}")
      print(answers[idx])
    else:
      print("I can't understand what you are saying. You see I am still learning.")

pip freeze